name = "facerec-wasm"
main = "build/worker/shim.mjs"
compatibility_date = "2025-02-13"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[r2_buckets]]
binding = "MODELS"
bucket_name = "models"
preview_bucket_name = "models"


[[r2_buckets]]
binding = "FACES"
bucket_name = "faces"
preview_bucket_name = "faces"

[assets]
directory = "./public"
binding = "ASSETS"

[durable_objects]
bindings = [
  { name = "SHARD1", class_name = "FaceNetShard1" }, # the `class_name` uses the Rust struct identifier name
  { name = "SHARD2", class_name = "FaceNetShard2" } # the `class_name` uses the Rust struct identifier name
]

[observability.logs]
enabled = true

[[vectorize]]
binding = "VECTORIZE"
index_name = "face-embeddings"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["FaceNetShard1", "FaceNetShard2" ] # Array of new classes
